language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: 
    secure:
    "AxH4EJ1fFNYdulU0UVYPbZXaLNIwdN5z0BClS+dAZWjGJFwB7YdtbHlwu74wOo0aEX8rxuztBtBRx7fj06Ka8wS6Pj91OznaSvwZTioPdc1xLdtEvZ/jTA3eSIKDfkB67KJuQvqO7lPd0GCUMh1VjJ8TsNIu7ZITvTHOSwBwoMm0urahPG472UdADIxV9EO5w20A+u1z2JWwNsbaeA3wyj92i6Odc66fzbO8NW3XDKeOSgQeN9bvBCz8NFu7qX27qiMwDYuHk8kNYpNLlDE6mKAqwnreIaE+ZLuwDLmQW1fPwdNsBXPqaDCY+sj5kMyXlpD3Ztk9atbFO0qHJmzzcYI01bXnBnzKmnH/fYOr8IMub5j7PJSx/dUD4PHdQldb5/M7+v4o5tsYv4v6XV2ccfZHa5GebgIMXVarnL3s5iVLbbQl75QUb99UCsrBT+3m+4hrODTsFQWX/v40kbJvPwiLeHlMTX43UbXjSQVPFvhePVyp9uBxDQvQEWJzFT8/hn4Y0iLn/dq0gdgrQG0d9CqF3gTYhk23GRTavljeW4W55IDi0bPG89uOKe0S7TsOL8I/iQSjArcVEyTFjJBYzAnwm2VCugqJCTAf8wyYJnORQDtv98z2NJpfLe73bMCFaHUyTVh1/SQM2tqgX/wsmTem4WmAryiN+VVFJBAiwrY="

  email:
    recipients:
      - leo.ramos.ari@gmai.com
      - r.a_leonardo@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provide: heroku
  skip-clean: true
  keep-history: true
  api_key:
    secure: "ZIxfwlayUGPq9CjfouWbi5LEtXovAt9xz4Z/GiIZfg9B+9+OuYTO6vaHfYEJMRAtWoqYh0SsAyBjN0nX/7t4udT3phREPF4snqgMtdB/YxoXS+CUdMirR4trW69TPiEEdUn1NE/UDJolvjTwhrwngU3naVTWIWeb7VJcGJ/3UUra0Hry2wDmZjdkD+DMNram69PLMITg8L0ztJNVfC5mfxnX2x9pbK1Hc7M5ik39YL6lcPGZTP+4vMlyHkV4ZmSYoDShwnGxnOxrxSQlNnifySeBmIRN+nRvKkd8a/eCTBmNnWmb6DZjLvMdRYnsi6oveFs+M6VBVeI/hy/CP5DDVyvIC3CQq3954YYHx4uNTV8gEnihCfjY9IlS45Q1AiLim5QQqllQ9uDJ+aT4k1PFx04/BYmqIdvOfWOthJU/K0tOKZpKz2DBr1/T+SFo9aIu4LWWOu57rGOnFdLdTFvDRi13N0cKfFJCNzlb7PRuxdKTWNGFc9DNDfU1l+eaWJj7lvKRTga8AHcNcwULsjdbdugM85lGLkKzHTHbjv9mssq5Yjyb2A5bdqM7oGHiOk4W64yYR3rEytE6pY6Z96c59gKbWq9foEH+rn2WkChcGCA5qkPUIjjkd0mPGyzKof59QQATrBUyi1p7OrRZd56826Qk1GrBnb0WZ/jlcjwtyck="
  app: project-store-backend
  on:
    repo: leoramosa/platzi-store-backend

